/**
 * biagiojs — generazione _headers per Cloudflare Pages / Netlify.
 * Usa `! Cache-Control` su asset statici: le regole CF si cumulano, non si sovrascrivono.
 */
const DEFAULT_IMMUTABLE = ['/img/*', '/fonts/*', '/islands/*', '/*.css'];
const DEFAULT_HTML = '/*.html';

export function generateHeaders(cache = {}) {
  const immutable = cache.immutable ?? DEFAULT_IMMUTABLE;
  const html = cache.html ?? DEFAULT_HTML;
  const htmlControl = cache.htmlControl ?? 'public, max-age=0, must-revalidate';
  const assetControl = cache.assetControl ?? 'public, max-age=31536000, immutable';

  const lines = [
    '# Generated by biagiojs — Cloudflare Pages / Netlify',
    '# Le regole si cumulano: ! forza Cache-Control anche se esiste /* generico.',
    '',
  ];

  for (const pattern of immutable) {
    lines.push(pattern, `  ! Cache-Control: ${assetControl}`, '');
  }
  lines.push(html, `  Cache-Control: ${htmlControl}`, '');
  return lines.join('\n');
}
