/** Coerenza rebrand biagiojs — superficie pubblica, path critici, assenza di nomi obsoleti. */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, mkdtempSync, mkdirSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname, extname } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import pkg from '../package.json' with { type: 'json' };
import { loadConfig } from '../src/core/config.js';
import { generateHeaders } from '../src/core/cache-headers.js';
import { collectSubsetText } from '../src/core/font-subset.js';
import { createBiagioServer, createCvwServer } from '../src/adapters/node.js';
import { compileBiagio, compileCvw, loadBiagioFile, loadCvwFile } from '../src/compiler.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = rel => readFileSync(join(root, rel), 'utf8');

function walkJs(dir, out = []) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walkJs(p, out);
    else if (extname(e.name) === '.js') out.push(p);
  }
  return out;
}

test('package.json: nome npm, bin CLI, versione e lockfile', () => {
  assert.equal(pkg.name, 'biagiojs');
  assert.equal(pkg.bin.biagio, 'src/cli.js');
  assert.equal(pkg.bin['create-biagiojs'], 'src/create-biagiojs.js');
  assert.equal(pkg.version, '0.10.1');
  const lock = JSON.parse(readFileSync(join(root, 'package-lock.json'), 'utf8'));
  assert.equal(lock.version, pkg.version, 'package-lock.json version deve coincidere con package.json');
  assert.equal(lock.packages[''].name, 'biagiojs', 'package-lock root name deve essere biagiojs');
});

test('package.json: repository GitHub biagiojs', () => {
  assert.match(pkg.repository.url, /github\.com\/Dani2097\/biagiojs/);
  assert.equal(pkg.repository.directory, 'biagiojs');
  assert.match(pkg.homepage, /github\.com\/Dani2097\/biagiojs/);
});

test('CLI: routing pagine .page.biagio e config biagio.config.js', () => {
  const cli = read('src/cli.js');
  assert.match(cli, /\.page\.(js|ts|biagio)/);
  assert.match(cli, /biagio\.config\.js/);
  assert.doesNotMatch(cli, /cvw\.config\.js/);
  assert.match(cli, /dependencies:\s*\{\s*'biagiojs'/);
  assert.doesNotMatch(cli, /'cvw-first'/);
  assert.match(cli, /loadBiagioFile/);
});

test('loadConfig supporta biagio.config.ts in config.js', () => {
  const cfg = read('src/core/config.js');
  assert.match(cfg, /biagio\.config\.ts/);
});

test('loadConfig legge biagio.config.js dal progetto', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'biagio-cfg-'));
  writeFileSync(join(dir, 'biagio.config.js'), `export default { site: { name: 'Test', baseUrl: 'https://t.dev' } };`);
  const cfg = await loadConfig(dir);
  assert.equal(cfg.site.name, 'Test');
});

test('generateHeaders: banner biagiojs, non CVW-First', () => {
  const out = generateHeaders();
  assert.match(out, /Generated by biagiojs/);
  assert.doesNotMatch(out, /CVW-First/);
});

test('font subset: scan include testo da pages/*.page.biagio', () => {
  const dir = mkdtempSync(join(tmpdir(), 'biagio-subset-'));
  const pages = join(dir, 'pages');
  mkdirSync(pages, { recursive: true });
  writeFileSync(join(pages, 'index.page.biagio'), '<page title="t" /><component id="x"><template>Žlutý biagiojs</template></component>');
  const text = collectSubsetText(dir, [], { preset: null, scan: true, extra: '' });
  assert.match(text, /Žlutý biagiojs/);
});

test('create-biagiojs scaffold standalone: delega a biagiojs/scaffold', () => {
  const scaffold = read('../create-biagiojs/index.js');
  assert.match(scaffold, /from 'biagiojs\/scaffold'/);
  assert.match(scaffold, /--template/);
  assert.match(scaffold, /await create\(dir, \{ template \}\)/);
  assert.doesNotMatch(scaffold, /cvw-first|cvw\.config/);
});

test('docs utente: AI-GUIDE e CHANGELOG senza CLI obsoleta', () => {
  for (const f of ['AI-GUIDE.md', 'CHANGELOG.md']) {
    const doc = read(f);
    assert.match(doc, /biagiojs/, `${f} deve menzionare biagiojs`);
    assert.doesNotMatch(doc, /npx cvw\b/, `${f} non deve usare npx cvw`);
  }
});

test('README: link documentazione (senza sezione migrazione)', () => {
  const readme = read('README.md');
  assert.doesNotMatch(readme, /## Migrazione da cvw-first/);
  assert.match(readme, /IMAGE-OPTIMIZATION\.md/);
  assert.match(readme, /DEPLOY-CACHE\.md/);
  assert.match(readme, /AI-GUIDE\.md/);
  assert.match(readme, /CHANGELOG\.md/);
});

test('src/: nessun prefisso errore [cvw] residuo', () => {
  const stale = [];
  for (const f of walkJs(join(root, 'src'))) {
    const src = readFileSync(f, 'utf8');
    if (/\[cvw[\]:]/.test(src)) stale.push(f.replace(root + '\\', '').replace(root + '/', ''));
  }
  assert.deepEqual(stale, [], `file con [cvw] residuo: ${stale.join(', ')}`);
});

test('adapter node: createBiagioServer esportato, createCvwServer alias', () => {
  assert.equal(typeof createBiagioServer, 'function');
  assert.equal(createCvwServer, createBiagioServer);
});

test('compiler: compileBiagio/loadBiagioFile primari, alias legacy', () => {
  assert.equal(typeof compileBiagio, 'function');
  assert.equal(compileCvw, compileBiagio);
  assert.equal(loadCvwFile, loadBiagioFile);
  const def = compileBiagio('<page title="t" description="d" /><component id="a" conversion="0.5"><template>x</template></component>').default();
  assert.equal(def.graph.nodes.size, 1);
});

test('runtime interno: API legacy cvw ancora presenti (breaking se rimosse)', () => {
  const hydration = read('src/core/hydration.js');
  assert.match(hydration, /__CVW_PLAN__/);
  assert.match(hydration, /data-cvw-id/);
  const signals = read('src/core/signals.js');
  assert.match(signals, /window\.cvw/);
});
